# Generated by Django 4.2.6 on 2024-08-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_authtoken_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
